server:
  port: 8003

# Mybatis配置
mybatis:
  type-aliases-package: com.hxr.springcloud.entity     # 所有Entity别名类所在包
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    cache-enabled: true #开启二级缓存


spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作系统
    driver-class-name: org.gjt.mm.mysql.Driver   # mysql驱动包
    url: jdbc:mysql://localhost:3306/study03  # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5   # 数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200      # 等待连接获取的最大超时时间
eureka:
#  server:  关闭自我保护
#    enable-self-preservation: false
  client: #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8003 # 自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
